terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  recoverTabs: false
  warnOnMultilinePaste: false
  environment: {}
  profile: bash
  workingDirectory: ''
  alwaysUseWorkingDirectory: false
hotkeys:
  profile:
    bash:
      - - ⌘-T
  ctrl-c:
    - - ⌘-Shift-C
  shell: {}
  toggle-window:
    - - ⌘-1
  ssh:
    - - Alt-S
    - - Ctrl-S
serial: {}
ssh:
  connections: []
appearance:
  dock: top
  dockSpace: 0.68
  dockFill: 0.6
  dockHideOnBlur: true
enableWelcomeTab: false
pluginBlacklist: []
